# Generated by Django 2.2.1 on 2019-05-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='avatar',
        ),
    ]
