# Generated by Django 2.2.1 on 2019-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20190517_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='short_url',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(max_length=5),
        ),
    ]
