# Generated by Django 2.2.1 on 2019-05-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_shorturl_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
