# Generated by Django 2.2.1 on 2019-05-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0012_shorturl_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='default',
            field=models.CharField(default='https://google.com', max_length=200),
        ),
    ]
