# Generated by Django 2.2.1 on 2019-05-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0013_auto_20190518_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(default=None, max_length=5, unique=True),
        ),
    ]
