# Generated by Django 2.2.1 on 2019-05-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(default='http://mind.now/', max_length=20),
            preserve_default=False,
        ),
    ]
