# Generated by Django 2.2.1 on 2019-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0011_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
