# Generated by Django 2.2.1 on 2019-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0014_auto_20190518_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='swiss_specific',
        ),
        migrations.AddField(
            model_name='link',
            name='country_specific',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
