# Generated by Django 2.2.1 on 2019-05-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0015_auto_20190519_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='click',
            name='shorturl_id',
        ),
        migrations.RemoveField(
            model_name='link',
            name='shorturl_id',
        ),
        migrations.AddField(
            model_name='click',
            name='link',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shortener.Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='click',
            name='short_url',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shortener.ShortURL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='short_url',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shortener.ShortURL'),
            preserve_default=False,
        ),
    ]
