# Generated by Django 2.2.1 on 2019-05-21 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0016_auto_20190521_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='user_id',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='short_url',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
