# Generated by Django 2.2.1 on 2019-05-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0017_auto_20190521_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='short_url',
            new_name='user',
        ),
    ]
