# Generated by Django 2.2.1 on 2019-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0018_auto_20190521_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='default',
        ),
        migrations.AddField(
            model_name='link',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
